version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "certificates:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
    restart: always
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    networks:
      - proxy-tier
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certificates:/etc/nginx/certs:rw"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
    restart: always

  lcapi:
    image: lansingcodes/lcapi
    env_file: lcapirc
    restart: always
    environment:
      LETSENCRYPT_HOST: lcapi.atomaka.com,api.lansing.codes
      LETSENCRYPT_EMAIL: me@atomaka.com
      VIRTUAL_HOST: lcapi.atomaka.com,api.lansing.codes
    networks:
      - proxy-tier
  lubot:
    image: lansingcodes/lubot
    env_file: lubotrc
    restart: always
  slackin:
    image: chk1/slackin
    env_file: slackinrc
    environment:
      LETSENCRYPT_HOST: lcslack.atomaka.com,slack.lansing.codes
      LETSENCRYPT_EMAIL: me@atomaka.com
      VIRTUAL_HOST: lcslack.atomaka.com,slack.lansing.codes
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
  certificates:
